"use client";

import Link from "next/link";
import { useState } from "react";
import { Icon } from "@/components/shared/icon";
import { Badge, Button, DemoStateControl, StateView } from "@/components/shared/ui";
import type { Appointment, LoadState, Medication } from "@/types";

export function PatientPageHeader({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <section className="portal-heading"><div className="container"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div></section>;
}

export function AppointmentLookup({ appointment, defaultMode = "lookup" }: { appointment: Appointment; defaultMode?: "lookup" | "book" }) {
  const [mode, setMode] = useState<"lookup" | "book">(defaultMode);
  const [searched, setSearched] = useState(false);
  const [booked, setBooked] = useState(false);
  const [state, setState] = useState<LoadState>("ready");
  return <div className="container portal-layout"><section className="portal-card lookup-card">
    <div className="appointment-mode" role="tablist" aria-label="Chọn tác vụ lịch khám"><button role="tab" aria-selected={mode === "book"} onClick={() => { setMode("book"); setSearched(false); }}>Đặt lịch khám</button><button role="tab" aria-selected={mode === "lookup"} onClick={() => { setMode("lookup"); setBooked(false); }}>Tra cứu lịch đã đặt</button></div>
    {mode === "lookup" ? <><div className="portal-card__heading"><span><Icon name="search"/></span><div><h2>Tìm lịch khám đã đặt</h2><p>Nhập thông tin trên lịch hẹn để tra cứu.</p></div></div><form onSubmit={(event) => { event.preventDefault(); setSearched(true); }} className="patient-form"><label><span>Số điện thoại</span><input required inputMode="tel" defaultValue="0987 000 042"/><small>Chỉ dùng số điện thoại giả trong bản dùng thử.</small></label><label><span>Mã lịch hẹn</span><input required defaultValue="HEN-260717-042"/></label><Button type="submit" icon="search">Tra cứu lịch khám</Button></form></> : <><div className="portal-card__heading"><span><Icon name="calendar"/></span><div><h2>Gửi yêu cầu đặt lịch</h2><p>Chọn nhu cầu dự kiến; nhân viên sẽ xác nhận lịch trong sản phẩm thật.</p></div></div>{booked ? <div className="booking-success" role="status"><span><Icon name="check"/></span><div><h3>Đã ghi nhận yêu cầu mô phỏng</h3><p>Mã yêu cầu <strong>YC-HEN-260717-018</strong>. Chưa có lịch thật được tạo và bệnh viện chưa nhận thông tin.</p><div className="result-actions"><Link className="button button--primary" href="/procedures#dat-lich">Xem bước chuẩn bị</Link><Button variant="secondary" onClick={() => setBooked(false)}>Tạo yêu cầu khác</Button></div></div></div> : <form className="booking-form" onSubmit={(event) => { event.preventDefault(); setBooked(true); }}><label><span>Họ và tên</span><input required defaultValue="Nguyễn Văn An"/><small>Chỉ nhập dữ liệu hư cấu khi xem bản dùng thử.</small></label><label><span>Số điện thoại</span><input required inputMode="tel" defaultValue="0987 000 042"/></label><label><span>Nhu cầu khám</span><select required defaultValue="tim-mach"><option value="tim-mach">Khám Tim mạch tổng quát</option><option value="tai-kham">Tái khám theo giấy hẹn</option><option value="tu-van">Cần nhân viên tư vấn chuyên khoa</option></select></label><label><span>Hình thức dự kiến</span><select defaultValue="bhyt"><option value="bhyt">Bảo hiểm y tế</option><option value="dich-vu">Dịch vụ</option></select></label><label><span>Ngày mong muốn</span><input required type="date" defaultValue="2026-07-20"/></label><label><span>Khung giờ mong muốn</span><select defaultValue="morning"><option value="morning">Buổi sáng</option><option value="afternoon">Buổi chiều</option></select></label><p className="form-note"><Icon name="shield" size={16}/> Đây là yêu cầu mô phỏng, không phải lịch hẹn đã xác nhận.</p><Button type="submit" icon="arrow">Gửi yêu cầu đặt lịch</Button></form>}</>}
    <div className="demo-row"><DemoStateControl state={state} setState={setState}/></div></section>
    <aside className="privacy-panel"><Icon name="shield"/><h2>Không nhập dữ liệu thật</h2><p>Bản dùng thử không gửi hoặc lưu dữ liệu biểu mẫu.</p><ul><li><Icon name="check"/> Không kết nối hệ thống bệnh viện</li><li><Icon name="check"/> Không lưu số điện thoại</li><li><Icon name="check"/> Dữ liệu hoàn toàn giả lập</li></ul><Link href="/procedures" className="text-button">Xem quy trình QT.25.01 <Icon name="arrow" size={14}/></Link></aside>
    {mode === "lookup" && searched && <section className="lookup-result portal-card" aria-live="polite">{state !== "ready" ? <StateView state={state} emptyText="Không tìm thấy lịch khám phù hợp." onRetry={() => setState("ready")}/> : <><div className="result-top"><div><Badge tone="success"><Icon name="check" size={13}/> {appointment.status}</Badge><h2>{appointment.department}</h2><p>Mã lịch hẹn: <strong>{appointment.id}</strong></p></div><span className="appointment-date"><strong>{appointment.time}</strong><small>{appointment.date}</small></span></div><dl className="appointment-details"><div><dt>Cơ sở khám</dt><dd><Icon name="map"/>{appointment.facility}</dd></div><div><dt>Bác sĩ dự kiến</dt><dd><Icon name="user"/>{appointment.doctor}</dd></div><div><dt>Hình thức</dt><dd><Icon name="file"/>{appointment.visitType} · {appointment.paymentType}</dd></div></dl><div className="result-actions"><Link className="button button--primary" href="/check-in"><Icon name="check"/> Xác nhận đã đến viện</Link><Link className="button button--secondary" href="/procedures#dang-ky"><Icon name="file"/> Xem giấy tờ cần chuẩn bị</Link></div></>}</section>}
  </div>;
}

export function MedicationList({ medications }: { medications: Medication[] }) {
  const [state, setState] = useState<LoadState>("ready");
  const [responses, setResponses] = useState<Record<string, string>>({});
  return <div className="container medication-page"><div className="profile-summary"><div className="avatar">NA</div><div><span>Hồ sơ giả lập</span><h2>Nguyễn Văn An</h2><p>Mã người bệnh: BN-DEMO-0042</p></div><DemoStateControl state={state} setState={setState}/></div><div className="medication-overview"><div><Icon name="pill"/><span><strong>{medications.length} lịch nhắc</strong><small>Đang hoạt động trong prototype</small></span></div><div><Icon name="check"/><span><strong>5/7 đã ghi nhận</strong><small>Trong 7 ngày gần đây</small></span></div><div><Icon name="bell"/><span><strong>Nhắc tiếp theo 20:00</strong><small>Chỉ hiển thị trên giao diện</small></span></div></div>{state !== "ready" ? <StateView state={state} emptyText="Chưa có lịch nhắc thuốc hôm nay." onRetry={() => setState("ready")}/> : <section><div className="content-heading"><div><h2>Lịch nhắc hôm nay</h2><p>Thứ Sáu, 17 tháng 07 năm 2026</p></div><Badge tone="info">Dữ liệu giả lập</Badge></div><div className="medication-list">{medications.map((medication) => <article className="medication-card" key={medication.id}><div className="med-time"><strong>{medication.time}</strong><span>{medication.status}</span></div><div className="med-main"><div className="med-title"><span><Icon name="pill"/></span><div><h3>{medication.name}</h3><p>{medication.dosage} · {medication.schedule}</p></div><Badge tone={medication.status === "Đã ghi nhận" ? "success" : medication.status === "Sắp đến giờ" ? "info" : "warning"}>{responses[medication.id] || medication.status}</Badge></div><div className="med-info"><p><strong>Hướng dẫn đã duyệt</strong>{medication.instruction}</p><p><strong>Thời gian áp dụng</strong>{medication.period}</p><p><strong>Người xác nhận</strong>{medication.approvedBy}</p></div><div className="med-actions" aria-label={`Ghi nhận cho ${medication.name}`}><span>Phản hồi:</span>{["Đã uống", "Chưa uống", "Không uống được", "Hết thuốc", "Có triệu chứng"].map((response) => <button className={responses[medication.id] === response ? "active" : ""} key={response} onClick={() => setResponses({ ...responses, [medication.id]: response })}>{response}</button>)}</div></div></article>)}</div><div className="medical-disclaimer"><Icon name="alert"/><p><strong>Prototype không đưa ra chỉ định y khoa</strong><span>Không tự thay đổi tên thuốc, liều hoặc giờ dùng. Nếu có dấu hiệu bất thường, gọi cơ sở y tế; trường hợp khẩn cấp gọi 115.</span></p></div></section>}</div>;
}
